<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_List users</name>
   <tag></tag>
   <elementGuidId>52aee5b3-56c5-4a4e-887c-1f38bf2778af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>611ac80f-d63c-44b0-8a5e-f84d510855e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>users</value>
      <webElementGuid>a5910707-6bb5-428a-80a5-eb7fbbd90144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>endpoint</value>
      <webElementGuid>5e4675a3-b79f-40da-a42c-0ac824d06ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-http</name>
      <type>Main</type>
      <value>get</value>
      <webElementGuid>716875f7-d862-4890-86e7-ab0908f40f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>db4edc47-ac1d-42b1-8f16-cd911ebc3b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         List users 
                    </value>
      <webElementGuid>666fd0f6-e0fb-41ba-a519-caeec1a763c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;endpoints&quot;]/ul[1]/li[@class=&quot;active&quot;]</value>
      <webElementGuid>a10739fc-90df-492e-b8ed-a645002112ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div/ul/li</value>
      <webElementGuid>436bb163-25d7-4863-98e1-a465025a576b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support ReqRes'])[1]/following::li[1]</value>
      <webElementGuid>ddb2eba8-8268-4076-b216-8990c1b23c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give it a try'])[1]/following::li[1]</value>
      <webElementGuid>d776ffb3-6fba-4408-ae53-cfca64a51be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single user'])[1]/preceding::li[1]</value>
      <webElementGuid>ca66645f-a168-43d7-98c0-b05f7d719127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>50fc3302-3955-4f13-9ec9-86be97bdf3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                         List users 
                    ' or . = '
                         List users 
                    ')]</value>
      <webElementGuid>4dd3b612-8129-41c7-b654-aabd9326b38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
