<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Register - successful</name>
   <tag></tag>
   <elementGuidId>6e722150-7402-434e-b794-3f1990253369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div/ul/li[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1c4317ba-a21e-42f1-bd2f-0074b9ce0089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>register-successful</value>
      <webElementGuid>e24038db-778d-48a3-a9f5-0221e53c7b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>endpoint</value>
      <webElementGuid>eb3bceeb-68b1-4e40-97a1-addbc83b9b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-http</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>bd3d7294-964f-4493-9a34-a276063b5eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Register - successful 
                    </value>
      <webElementGuid>93fdd752-dcd3-4c52-a44a-50ca5d61e8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;endpoints&quot;]/ul[1]/li[11]</value>
      <webElementGuid>9b84b4cc-5fa0-4792-99ad-4dc3bee63260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div/ul/li[11]</value>
      <webElementGuid>8acc356b-8493-4348-8492-6e665d868f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::li[1]</value>
      <webElementGuid>d9dfea28-c7ea-41fd-bfe8-608b00f4d06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[2]/following::li[2]</value>
      <webElementGuid>f5fe6098-9b65-4b4e-9ff1-af2386328eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register - unsuccessful'])[1]/preceding::li[1]</value>
      <webElementGuid>202a51e8-f116-46c2-8ea7-8ac8a5fe3108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]</value>
      <webElementGuid>1b5b361c-efeb-420d-b855-320a7a041571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                         Register - successful 
                    ' or . = '
                         Register - successful 
                    ')]</value>
      <webElementGuid>da188641-5123-4e88-961a-27994f9c8706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
